version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile.apache
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.mydb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql12345
      MYSQL_DATABASE: selling_computer
      MYSQL_USER: trannguyenhan
      MYSQL_PASSWORD: mysql12345
    ports:
      - "9906:3306"
